### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by bhaap** [c727/home-assistant-tiles#1]
I am unable to get this to work. 

Does this work with 0.59 of home assistant still?

**Comment by c727** [comment]
yes

**Comment by bhaap** [comment]
I've copied the html file to the correct dir and this is my config.
```yaml
homeassistant:
  customize:
    input_text.dummy_tiles:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 3
        column_width: 75px
        row_height: 75px
        entities:
          - entity: switch.eluttag1
            label: UB
            column: 3
            row_span: 3
groups:
  tiles_view:
    view: yes
    icon: mdi:rhombus-outline
    entities:
      - group.g1
  g1:
    name: Tiles
    entities:
      - input_text.dummy_tiles
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
input_text:
  dummy_tiles:
    name: dummy
```

Anything I've missed?

**Comment by c727** [comment]
```
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles.html
```
Also try Ctrl+F5
