### ISSUE TITLE
Gap is only applied between rows if height/widht are specified.

### ISSUE THREAD

**Issue by luca-angemi** [c727/home-assistant-tiles#10]
# Incomplete issues will be ignored
- [X ] I have read README.md
- [ X] I have deleted my browser cache after updating tiles

**Description of problem:**
```
Gap is only applied between rows if height/widht are specified.
```

**Expected:**
```
Gap applied to the entire grid.
```

**Tiles version:**
```
Latest
```

**Affected browser:**
```
Chrome 
```

**Home Assistant version:**
```
63.3
```

**Home Assistant `frontend:` config:**
```yaml
frontend:
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles.html
```

**Home Assistant `customize:` config:**
```yaml
script.camera_button:
  custom_ui_state_card: state-card-tiles
  config:
    columns: 5
    column_width: 55px
    gap: 5px
    row_height: 55px
    entities:
    - entity: script.camera_up
      icon: mdi:arrow-up-thick
      column: 3
    - entity: script.camera_left
      icon: mdi:arrow-left-thick
      column: 2
    - entity: script.camera_down
      icon: mdi:arrow-down-thick
      column: 3
    - entity: script.camera_right
      icon: mdi:arrow-right-thick
      column: 4
```

**Error log from browser dev console - NOT from HA:**
```
<<here>>
```

**Screenshot:**
![image](https://user-images.githubusercontent.com/9977955/36787432-68eee49c-1c8a-11e8-90db-35e85d7799ba.png)
