### ISSUE TITLE
Clicking on buttons will open the history card.

### ISSUE THREAD

**Issue by luca-angemi** [c727/home-assistant-tiles#11]
# Incomplete issues will be ignored
- [X] I have read README.md
- [X]  I have deleted my browser cache after updating tiles

**Description of problem:**
```
When clicking on a button the history card of the group pops up.
```

**Expected:**
```
No card should open.
```

**Tiles version:**
```
latest
```

**Affected browser:**
```
Chrome
```

**Home Assistant version:**
```
63.3
```

**Home Assistant `frontend:` config:**
```yaml
frontend:
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles.html
```

**Home Assistant `customize:` config:**
```yaml
script.camera_button:
  custom_ui_state_card: state-card-tiles
  config:
    columns: 3
    column_width: 57px
    gap: 4px
    row_height: 57px
    entities:
    - entity: script.camera_up
      icon: mdi:arrow-up-thick
      column: 2
    - entity: script.camera_left
      icon: mdi:arrow-left-thick
      column: 1
    - entity: script.camera_down
      icon: mdi:arrow-down-thick
      column: 2
    - entity: script.camera_right
      icon: mdi:arrow-right-thick
      column: 3
```

**Error log from browser dev console - NOT from HA:**
```
N/A
```

**Screenshot:**
After click on any button

![image](https://user-images.githubusercontent.com/9977955/36816744-100ce78e-1cdf-11e8-960b-1aaf8a21907d.png)
