### ISSUE TITLE
How to show these images as buttons?

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#12]
HI, 

im trying your Tiles custom-ui but have a question about the side panel functionality I am trying to achieve through the code below. 

The buttons show, but the icons are deeply zoomed in, and I can only see a small part of them. How do I show the full icon, in the correct size of the button. I've added these image file as an example.
tried to reduce the size to 12 px, but no such luck.....

![hometheater](https://user-images.githubusercontent.com/33354141/36946512-31c1df92-1fbe-11e8-9f19-7b87a3751ea9.png)
![opstaan](https://user-images.githubusercontent.com/33354141/36946513-31e28f4e-1fbe-11e8-8512-0ded6402d4c3.png)
![selamatmakan](https://user-images.githubusercontent.com/33354141/36946514-31fec31c-1fbe-11e8-918e-efbaf20c135d.png)

![schermafbeelding 2018-03-04 om 15 13 24](https://user-images.githubusercontent.com/33354141/36946544-a783ab52-1fbe-11e8-9985-1a9889b6296d.jpg)

```
name: tiles
sidebar_title: Tiles
sidebar_icon: mdi:view-dashboard
url_path: tiles
config:
  columns: 4
  column_width: 75px
  row_height: 75px
  gap: 4px
  color: lightgrey
  color_on: green
  color_off: red
  text_color: "#FFF"
  text_color_on: "#FFF"
  text_color_off: "#FFF"
  text_size: 1em
  text_sec_color: "#FFF"
  text_sec_size: 1em
  text_align: center | left | right
  icon_size: 12px
  entities:
    - entity: script.opstaan
      label: Opstaan
      image: /local/activities/opstaan.png
    - entity: script.aan_de_slag
      label: Aan de slag!
      image: /local/activities/aandeslag.png
    - entity: script.uit_huis
      label: Uit huis
      image: /local/activities/uithuis.png
    - entity: script.gym
      label: Gym
      image: /local/activities/gym.png
    - entity: script.selamat_makan
      label: Selamat makan
      image: /local/activities/selamatmakan.png
    - entity: script.home_theater
      label: Home theater
      image: /local/activities/hometheater.png
    - entity: script.naar_bed
      label: Naar bed
      image: /local/activities/naarbed.png
    - entity: group.summary
      label: Summary
```
