### ISSUE TITLE
No State History Found pop-up

### ISSUE THREAD

**Issue by jarrah31** [c727/home-assistant-tiles#15]
# Incomplete issues will be ignored
- [x] I have read README.md
- [x] I have deleted my browser cache after updating tiles

**Description of problem:**
```
No State History Found pop-up when pressing a button
```

**Expected:**
```
No pop-up
```

**Tiles version:**
```
Version: 20180228
```

**Affected browser:**
```
Safari (Mac and iOS), Chrome
```

**Home Assistant version:**
```
0.62.1
```

**Home Assistant `frontend:` config:**
```configuration.yamlyaml
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html
```

**Home Assistant `customize:` config:**
```yaml
  customize:
    script.remote_control:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 7
        row_height: 75px
        column_width: 62px
        gap: 15px
        color: '#555B65'
        color_on: '#F0C209'
        color_off: '#555B65'
        entities:
          #Lights
          - entity: switch.study_lights
            label: Study
            icon: mdi:school
            column: 1
            row: 1
```

**Error log from browser dev console - NOT from HA:**
```
N/A
```

**Screenshot:**
\<\<here>>
<img width="186" alt="screen shot 2018-03-07 at 16 39 25" src="https://user-images.githubusercontent.com/3072303/37105672-b2ebdbd4-2227-11e8-92ab-ac7f91a03051.png">

**Comment by c727** [comment]
try this:
![try this](https://user-images.githubusercontent.com/11984118/37107443-a03f8a32-2234-11e8-9f3a-66ccab7bff88.PNG)

**Comment by PostSven** [comment]
@c727 This does not help on the IOS application (It is showing same behavior).

**Comment by jarrah31** [comment]
Hi c727, 

I removed the cookies on Chrome as requested and interestingly it shows a different pop-up now:

<img width="367" alt="screen shot 2018-03-08 at 10 24 54" src="https://user-images.githubusercontent.com/3072303/37146287-32f10910-22bb-11e8-998e-5688f3ddc8e6.png">

On iOS I'm using the Home Assistant app and this too show the updated pop-up.

So there must be something in my config that causes the pop-up to appear. Other people on the forum are reporting the same issue.

I have a very basic test Tile config so far as I'm just starting to use the new UI, so here is what I'm using:

Here is my initial test controlpanel.yaml file in /home/homeassistant/.homeassistant/packages/

`homeassistant:
  customize:
    script.remote_control:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 7
        row_height: 75px
        column_width: 62px
        gap: 15px
        color: '#555B65'
        color_on: '#F0C209'
        color_off: '#555B65'
        entities:
          #Lights
          - entity: switch.study_lights
            label: Study
            icon: mdi:school
            column: 1
            row: 1

script:
  remote_control:
    sequence:

group:
  remote_control:
    name: Control Panel
    entities:
      - script.remote_control
  study_lamps:
    name: Study Lamps
    entities:
      - light.study_desk_lamp
      - switch.tplink_sw4

switch:
  - platform: template
    switches:
      study_lights:
        value_template: "{{ is_state('group.study_lamps', 'on') }}"
        turn_on:
          service: homeassistant.turn_on
          data:
            entity_id: group.study_lamps
        turn_off:
          service: homeassistant.turn_off
          data:
            entity_id: group.study_lamps`

My configuration.yaml has the following:

`homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: !secret homeassistant_timezone
  customize: !include customize.yaml
  packages: !include_dir_named packages/

frontend:
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html`

**Comment by c727** [comment]
Version: 20180308
```
-fix dialog for old HA releases
```

**Comment by c727** [comment]
Btw: you don't need a template switch in tiles for groups anymore (since some releases)

**Comment by jarrah31** [comment]
superb, thank you very much!! I'll test the updated version in a moment... (I should update HA too).

Also thanks for the config suggestion - I read in an earlier post that groups didn't work so didn't even try it. I've now put the group direct into the tile entity and it works a treat.

**Comment by jarrah31** [comment]
Speaking of improving my example, I notice that your configuration.yaml uses input_boolean instead of script (which I took from an earlier post). Is input_boolean the preferred method?
```
homeassistant:
  customize:
    input_boolean.tiles_showcase:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 3
```

**Comment by jarrah31** [comment]
Just tried the new version but unfortunately it doesn't appear to be working. These are the steps I followed to update the code:

1. git fetch within the /home/pi/home-assistant-tiles dir
2. sudo cp www/custom_ui/state-card-tiles* /home/homeassistant/.homeassistant/www/custom_ui/
3. Confirmed files has been updated and permissions were correct:
```
pi@hassbian:~/home-assistant-tiles $ ls -al /home/homeassistant/.homeassistant/www/custom_ui/
total 44
drwxr-xr-x 3 homeassistant homeassistant 4096 Mar  6 18:06 .
drwxr-xr-x 5 homeassistant homeassistant 4096 Mar  2 15:56 ..
-rw-r--r-- 1 homeassistant homeassistant 9234 Mar  8 13:08 state-card-tiles_es5.html
-rw-r--r-- 1 homeassistant homeassistant 9231 Mar  8 13:08 state-card-tiles.html
```
4. Restarted home assistant service
5. Test button - pop-up shows again.
6. Confirmed updated code in state-card-tiles.html
```
    <paper-button-group on-click='stopPropagation'>
      <template is='dom-repeat' items='[[stateObj.attributes.config.entities]]' as='entity'>
        <paper-button raised class$='[[computeClass(hass, entity)]]' style$='[[computeStyle(entity)]][[computeStyleTemplate(hass, entity)]]' on-click='buttonClicked'>
          <div>
            <template is='dom-if' if='[[entity.icon]]'>
```
It's not essential I use the older HA version so could upgrade if that's the fix?

**Comment by jarrah31** [comment]
Just to add to this, I updated my yaml to use input_boolean and now the following occurs in the pop-up:
<img width="369" alt="screen shot 2018-03-08 at 13 29 10" src="https://user-images.githubusercontent.com/3072303/37153511-d7ed7bba-22d4-11e8-9b20-95cdebe60273.png">
```
homeassistant:
  customize:
    input_boolean.remote_control:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 7
        row_height: 75px
        column_width: 62px
        gap: 15px
        color: '#555B65'
        color_on: '#F0C209'
        color_off: '#555B65'
        entities:
          #Lights
          - entity: switch.study_lights
            label: Study
            icon: mdi:school
            column: 1
            row: 1

input_boolean:
  remote_control:

group:
  remote_control:
    name: Control Panel
    entities:
      - input_boolean.remote_control
  study_lamps:
    name: Study Lamps
    entities:
      - light.study_desk_lamp
      - switch.tplink_sw4
```
