### ISSUE TITLE
Chrome doesn't show switch buttons color

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#18]
And messes up the icons too along the way...

Safari:

![schermafbeelding 2018-03-08 om 23 25 08](https://user-images.githubusercontent.com/33354141/37180061-029e6682-2328-11e8-80ec-525ae7c74ac4.jpg)

Chrome:

![schermafbeelding 2018-03-08 om 23 25 19](https://user-images.githubusercontent.com/33354141/37180076-096fdf5e-2328-11e8-91cd-24e4d9ba60db.jpg)

relevant code:

```
name: tiles
sidebar_title: Tiles
sidebar_icon: mdi:view-dashboard
url_path: tiles_multi
config:
  columns: 4
  column_width: 75px
  row_height: 75px
  gap: 4px
  color: lightgrey
  color_on: green
  color_off: red
  text_color: "#FFF"
  text_color_on: "#FFF"
  text_color_off: "#FFF"
  text_size: 1em
  text_sec_color: "#FFF"
  text_sec_size: 1em
  text_align: center | left | right
  icon_size: 24px
```

**Comment by c727** [comment]
post the whole code please

**Comment by hvbhome** [comment]
trying the multi setup also, must be something wrong ;-)

![schermafbeelding 2018-03-08 om 23 46 40](https://user-images.githubusercontent.com/33354141/37180882-f98d1a4a-232a-11e8-8047-e001f2b3563f.jpg)


name: tiles
sidebar_title: Tiles
sidebar_icon: mdi:view-dashboard
url_path: tiles
config:
  columns: 4
  column_width: 75px
  row_height: 75px
  gap: 4px
  color: lightgrey
  color_on: green
  color_off: red
  text_color: "#FFF"
  text_color_on: "#FFF"
  text_color_off: "#FFF"
  text_size: 1em
  text_sec_color: "#FFF"
  text_sec_size: 1em
  text_align: center | left | right
  icon_size: 24px
  multi:
    - header: Activities
#      row:
#      row_span:
#      column:
#      column_span:
      tiles:
        columns: 4
        entities:
          - entity: script.opstaan
            # label: Opstaan
            image: /local/activities/opstaan75.png
          - entity: script.aan_de_slag
            # label: Aan de slag!
            image: /local/activities/aandeslag75.png
          - entity: script.uit_huis
            # label: Uit huis
            image: /local/activities/uithuis75.png
          - entity: script.gym
           # label: Gym
            image: /local/activities/gym75.png
          - entity: script.selamat_makan
           # label: Selamat makan
            image: /local/activities/selamatmakan75.png
          - entity: script.home_theater
           # label: Home theater
            image: /local/activities/hometheater75.png
          - entity: script.naar_bed
          #  label: Naar bed
            image: /local/activities/naarbed75.png
          - entity: switch.sw_tv_auditorium_cl
            icon: mdi:theater
            label: Tv Auditorium

    - header: Switches
#      row:
#      row_span:
#      column:
#      column_span:
      tiles:
        columns: 4
        entities:
          - entity: switch.sw_audio_auditorium_template
            label: Audio Auditorium
            icon: mdi:theater
          - entity: switch.sw_tv_auditorium_template
            label: Tv Auditorium
            icon: mdi:television
          - entity: switch.sw_espresso_keuken_template
            label: Espresso
            icon: mdi:coffee
          - entity: switch.sw_tv_library_template
            label: Tv Library
            icon: mdi:television
          - entity: switch.sw_kantoor_template
            label: Kantoor
            icon: mdi:desktop-mac
          - entity: switch.sw_audio_gym_template
            label: Audio Gym
            icon: mdi:speaker
          - entity: switch.sw_tester_template
            label: Tester
            icon: mdi:test-tube
          - entity: switch.sw_dorm_template
            label: Dorm
            icon: mdi:human-child

**Comment by c727** [comment]
```yaml
  name: tiles
  sidebar_title: Tiles
  sidebar_icon: mdi:view-dashboard
  url_path: tiles
  config:
    columns: 2
    rows: 2
    gap: 4px
    multi:
      - header: Activities
        row: 1
        row_span: 2
        column: 1
        column_span: 1
        tiles:
          columns: 4
          color: lightgrey
          color_on: green
          color_off: red
          entities:
            - entity: script.opstaan
              # label: Opstaan
              image: /local/activities/opstaan75.png
            - entity: script.aan_de_slag
              # label: Aan de slag!
              image: /local/activities/aandeslag75.png
            - entity: script.uit_huis
              # label: Uit huis
              image: /local/activities/uithuis75.png
            - entity: script.gym
             # label: Gym
              image: /local/activities/gym75.png
            - entity: script.selamat_makan
             # label: Selamat makan
              image: /local/activities/selamatmakan75.png
            - entity: script.home_theater
             # label: Home theater
              image: /local/activities/hometheater75.png
            - entity: script.naar_bed
            #  label: Naar bed
              image: /local/activities/naarbed75.png
            - entity: switch.sw_tv_auditorium_cl
              icon: mdi:theater
              label: Tv Auditorium

      - header: Switches
        row: 2
        row_span: 1
        column: 2
        column_span: 1
        tiles:
          columns: 4
          color: lightgrey
          color_on: green
          color_off: red
          entities:
            - entity: switch.sw_audio_auditorium_template
              label: Audio Auditorium
              icon: mdi:theater
            - entity: switch.sw_tv_auditorium_template
              label: Tv Auditorium
              icon: mdi:television
            - entity: switch.sw_espresso_keuken_template
              label: Espresso
              icon: mdi:coffee
            - entity: switch.sw_tv_library_template
              label: Tv Library
              icon: mdi:television
            - entity: switch.sw_kantoor_template
              label: Kantoor
              icon: mdi:desktop-mac
            - entity: switch.sw_audio_gym_template
              label: Audio Gym
              icon: mdi:speaker
            - entity: switch.sw_tester_template
              label: Tester
              icon: mdi:test-tube
            - entity: switch.sw_dorm_template
              label: Dorm
              icon: mdi:human-child
```

**Comment by hvbhome** [comment]
click...rebooting...

**Comment by c727** [comment]
```yaml
  name: tiles
  sidebar_title: Tiles
  sidebar_icon: mdi:view-dashboard
  url_path: tiles
  config:
    columns: 1
    rows: 2
    gap: 4px
    multi:
      - header: Activities
        tiles:
          columns: 4
          color: lightgrey
          color_on: green
          color_off: red
          entities:
            - entity: script.opstaan
              # label: Opstaan
              image: /local/activities/opstaan75.png
            - entity: script.aan_de_slag
              # label: Aan de slag!
              image: /local/activities/aandeslag75.png
            - entity: script.uit_huis
              # label: Uit huis
              image: /local/activities/uithuis75.png
            - entity: script.gym
             # label: Gym
              image: /local/activities/gym75.png
            - entity: script.selamat_makan
             # label: Selamat makan
              image: /local/activities/selamatmakan75.png
            - entity: script.home_theater
             # label: Home theater
              image: /local/activities/hometheater75.png
            - entity: script.naar_bed
            #  label: Naar bed
              image: /local/activities/naarbed75.png
            - entity: switch.sw_tv_auditorium_cl
              icon: mdi:theater
              label: Tv Auditorium

      - header: Switches
        tiles:
          columns: 4
          color: lightgrey
          color_on: green
          color_off: red
          entities:
            - entity: switch.sw_audio_auditorium_template
              label: Audio Auditorium
              icon: mdi:theater
            - entity: switch.sw_tv_auditorium_template
              label: Tv Auditorium
              icon: mdi:television
            - entity: switch.sw_espresso_keuken_template
              label: Espresso
              icon: mdi:coffee
            - entity: switch.sw_tv_library_template
              label: Tv Library
              icon: mdi:television
            - entity: switch.sw_kantoor_template
              label: Kantoor
              icon: mdi:desktop-mac
            - entity: switch.sw_audio_gym_template
              label: Audio Gym
              icon: mdi:speaker
            - entity: switch.sw_tester_template
              label: Tester
              icon: mdi:test-tube
            - entity: switch.sw_dorm_template
              label: Dorm
              icon: mdi:human-child
```
in `config` you define the main grid in the dashboard (was 2x2), in `multi` you define the position/size for the specific sub-tiles

I dont know whats wrong in your chrome, looks like an cache issue. join the discord chat and PM me if you need more help https://discord.gg/c5DvZ4e
