### ISSUE TITLE
Spanning rows and button thickness problem/question

### ISSUE THREAD

**Issue by jarrah31** [c727/home-assistant-tiles#19]
# Incomplete issues will be ignored
- [x] I have read README.md
- [x] I have deleted my browser cache after updating tiles

**Description of problem:**

Would you mind helping me figure out where I'm going wrong please? I'm trying to create a thin tile that spans all three columns that is half the size of the other tiles.
At the moment my configuration looks like this:
<img width="211" alt="screen shot 2018-03-09 at 14 55 09" src="https://user-images.githubusercontent.com/3072303/37213436-ed0fd544-23a9-11e8-8f4c-2c24c0246809.png">
I would like Kitchen All to be half the size of the other buttons.

I have tried isolating just that tile to make it thinner by changing the row_height to as low as 5px, but it always stays the same. I tried removing the icon and text, but I still couldn't make it thinner. Am I perhaps assuming wrongly that row-height adjusts tile height?

As seen in the config below, I've also tried spanning rows to make the other buttons double sized, but that made no difference on the size because row_height doesn't seem to be having any effect.

I'm basically trying to make a button as thin as this example:
![24ef6638c44ff2c68c64ceee4ea05033db4ce75e](https://user-images.githubusercontent.com/3072303/37211162-f631195a-23a2-11e8-9096-e06b9d482505.gif)

Also, how can I make the labels lowercase?

**Expected:**
```

```

**Tiles version:**
```
Version:  20180308
```

**Affected browser:**
```
Safari (Mac and iOS), Chrome
```

**Home Assistant version:**
```
0.62.1
```

**Home Assistant `frontend:` config:**
```configuration.yaml
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html
```

**Home Assistant `customize:` config:**
```yaml
  homeassistant:
  customize:
    input_text.lights:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 3
        # row_height: 75px
        row_height: 45px
        # column_width: 75px
        gap: 15px
        text_size: 1em
        color: '#555B65'
        color_on: '#F0C209'
        color_off: '#555B65'
        entities:
          #Lights
          - entity: group.lounge_lights
            label: Lounge
            icon: mdi:ceiling-light
            column: 1
            row: 1
            row-span: 2
          - entity: group.lounge_lamps
            label: Lounge
            icon: mdi:lamp
            column: 2
            row: 1
            row-span: 2
          - entity: group.study_lamps
            label: Study
            icon: mdi:school
            column: 3
            row: 1
            row-span: 2
          - entity: group.kitchen_lights_all
            label: Kitchen
            icon: mdi:lightbulb
            column_span: 3
            row: 3
          - entity: light.kitchen
            label: Kitchen
            icon: mdi:door
            column: 1
            row: 4
            row-span: 2
          - entity: light.kitchen_main_led
            label: Kitchen
            icon: mdi:led-strip
            column: 2
            row: 4
            row-span: 2
          - entity: group.kitchen_spots
            label: Kitchen
            icon: mdi:spotlight-beam
            column: 3
            row: 4
            row-span: 2
          - entity: group.hall_lights
            label: Hall
            icon: mdi:ceiling-light
            column: 1
            row: 6
            row-span: 2
          - entity: group.landing_lights
            label: Landing
            icon: mdi:ceiling-light
            column: 2
            row: 6
            row-span: 2
```

**Error log from browser dev console - NOT from HA:**
```
N/A
```

**Comment by c727** [comment]
- minimum button size is 50x50px
- `row_span`
- material buttons are uppercase, however try style_template

**Comment by jarrah31** [comment]
- Ah, thanks for letting me know about the minimum button size. I'm still curious to know how the animated gif screenshot example above managed to make that thin "ROOM" button with an icon. I've adjusted my config to `row_height: 50px` but the height hasn't changed - can it go thinner? 
<img width="352" alt="screen shot 2018-03-09 at 17 27 36" src="https://user-images.githubusercontent.com/3072303/37220764-8b699972-23bf-11e8-847f-386209d501c5.png">
- Can't believe I made such an obvious typo - thank you for the row_span correction. :) 
- I'm not quite sure how to adapt style_template into text. I see from the example it looks like this:
`style_template: "if (state !== 'on') return 'text-decoration: line-through';"`
So I tried this, but it didn't work. Any ideas please?
`style_template: "return 'Kitchen All'"`

Thank you!

**Comment by c727** [comment]
Untested: `"return 'text-transform: none;';"`

**Comment by jarrah31** [comment]
Sorry, I didn't mean to close the issue as I'm still not sure how to make a thin button? It looks like others in the forum thread have a tile that's smaller than 50x50, but this is as small as I can get:
<img width="354" alt="screen shot 2018-03-09 at 19 38 43" src="https://user-images.githubusercontent.com/3072303/37226423-c6c46878-23d1-11e8-86f2-f15f860b4002.png">
Using this code:
```
    input_text.test:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 1
        row_height: 50px
        column_width: 50px
        gap: 15px
        entities:
          #Lights
          - entity: switch.kitchencam_sw
            label: Test
            style_template: "return 'text-transform: none;';"
```
Regarding the lowercase text, I can confirm that your suggestion works, thank you!!
