### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mf-social** [c727/home-assistant-tiles#2]
Hi,

Thanks for this repo, has really tidied up my frontend!

I was wondering if I could make a feature request though please...

It would be good if you could add the colour options to individual buttons as an override:

```
homeassistant:
  customize:
    input_text.dummy_tiles:
      custom_ui_state_card: state-card-tiles
      config:
        color: blue         # 
        color_on: green     # Default colours for this, see below...
        color_off: red      #
        entities:
          - entity: script.one
            label: S1       
            icon: mdi:power 
          - entity: script.two
            label: S2       
            icon: mdi:power 
          - entity: script.three     #
            label: S3                # This button is 'special' so
            icon: mdi:power          # has different colours 
            color_on: purple         #  S1, S2 and S4 follow the default
            color_off: orange        # but S3 has it's own colours
          - entity: script.four      #
            label: S4       
            icon: mdi:power 
```

For your consideration.
