### ISSUE TITLE
Align text below icon?

### ISSUE THREAD

**Issue by jarrah31** [c727/home-assistant-tiles#22]
# Incomplete issues will be ignored
- [x] I have read README.md
- [x] I have deleted my browser cache after updating tiles

**Description of problem:**
Is it possible to manually have text aligned below the icon please? At the moment my tiles look like the screenshot below where some have text to the right and some are below, depending on text length.
<img width="212" alt="screen shot 2018-03-11 at 21 31 32" src="https://user-images.githubusercontent.com/3072303/37258898-e50cf51a-2576-11e8-88c5-a04ce02c34e7.png">

**Tiles version:**
```
20180308
```

**Affected browser:**
```
N/A
```

**Home Assistant version:**
```
0.62.1
```

Code:
```
homeassistant:
  customize:
    input_text.lights:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 3
        # row_height: 75px
        row_height: 25px
        # column_width: 75px
        gap: 10px
        text_size: 1em
        color: '#555B65'
        color_on: '#F0C209'
        color_off: '#555B65'
        entities:
          #Lights
          - entity: group.lounge_lights
            label: Lounge
            icon: mdi:ceiling-light
            column: 1
            row: 1
            row_span: 2
          - entity: group.lounge_lamps
            label: Lounge
            icon: mdi:lamp
            column: 2
            row: 1
            row_span: 2
          - entity: group.study_lamps
            label: Study
            icon: mdi:school
            column: 3
            row: 1
            row_span: 2
          - entity: group.kitchen_lights_all
            label: Kitchen All
            style_template: "return 'text-transform: none; min-height: 25px;';"
            icon: mdi:power
            column_span: 3
            row: 3
          - entity: light.kitchen
            label: Kitchen
            icon: mdi:door
            column: 1
            row: 4
            row_span: 2
          - entity: light.kitchen_main_led
            label: Kitchen
            icon: mdi:led-strip
            column: 2
            row: 4
            row_span: 2
          - entity: group.kitchen_spots
            label: Kitchen
            icon: mdi:spotlight-beam
            column: 3
            row: 4
            row_span: 2
          - entity: group.hall_lights
            label: Hall
            icon: mdi:ceiling-light
            column: 1
            row: 6
            row_span: 2
          - entity: group.landing_lights
            label: Landing
            icon: mdi:ceiling-light
            column: 2
            row: 6
            row_span: 2
          - entity: light.bed_two
            label: Bed2
            icon: mdi:ceiling-light
            column: 1
            row: 8
            style_template: "return 'text-transform: none; min-height: 25px;';"
          - entity: light.bedside2
            label: Bed2
            icon: mdi:lamp
            column: 2
            row: 8
            style_template: "return 'text-transform: none; min-height: 25px;';"
          - entity: switch.bed_two_floor_light
            label: Bed2
            icon: mdi:power-plug
            column: 3
            row: 8
            style_template: "return 'text-transform: none; min-height: 25px;';"
          - entity: light.bed_three
            label: Bed3
            icon: mdi:ceiling-light
            column: 1
            row: 9
            style_template: "return 'text-transform: none; min-height: 25px;';"
          - entity: light.bedside3
            label: Bed3
            icon: mdi:lamp
            column: 2
            row: 9
            style_template: "return 'text-transform: none; min-height: 25px;';"
          - entity: switch.bed_three_floor_light
            label: Bed3
            icon: mdi:power-plug
            column: 3
            row: 9
            style_template: "return 'text-transform: none; min-height: 25px;';"
```
Thank you!
