### ISSUE TITLE
update automation correct?

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#23]
HI,

Wouldn't the update automation in your instruction page need an extra condition to check and compare to there currently installed version? seems it only reads the latest version (without comparing to the installed version?)

```
automation:
  - alias: SC Tiles update info
    trigger:
      platform: state
      entity_id: sensor.sc_tiles_latest_version
    action:
      service: persistent_notification.create
      data:
        title: Update available
        message: A new version for [Tiles custom state card](https://github.com/c727/home-assistant-tiles#changelog) is available.
```

must we create a template sensor, something like the HA update itself?
```

  - platform: template
    sensors:
      ha_update_available:
        friendly_name: 'HA Update Available'
#        unit_of_measurement: '{{states.sensor.ha_latest_version.state}}'
        value_template: >-
          {%- if states.sensor.ha_latest_version.state != "unavailable" and 
          states.sensor.ha_latest_version.state != states.sensor.ha_installed_version.state -%}
             Yes
          {%- else -%}
             No
          {%- endif -%}
        icon_template: >-
          {%- if states.sensor.ha_latest_version.state != "unavailable" and 
          states.sensor.ha_latest_version.state != states.sensor.ha_installed_version.state -%}
            mdi:alert-box
          {% else %}
            mdi:approval
          {% endif %}
```
