### ISSUE TITLE
side-panel gap size for main grid and tiles grid?

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#25]
hi,

struggling somewhat with the positions and relative spacing of tiles in the side-panel.

Not sure whether the gap: xx is for the vertical distance between the main grid rows only.
specific settings for the set of tiles seem to be added, or at least interfering with this?

just to be sure id like to ask if the horizontal gap between tiles can be adjusted too, or is that automatic and only depending on the amount of tiles and the column width.

iow:
can we declare a main_grid_gap: horizontal and main_grid_gap: vertical,
and
tile_grid_gap: horizontal and tile_grid_gap: vertical

since the regular tiles are in a group the main grid spacing might be less needed, still the question about the tile_grid would be valid also.

Cheers,
Marius

**Comment by c727** [comment]
screenshot please

**Comment by hvbhome** [comment]
Pardon my shortness but i am away... see https://community.home-assistant.io/t/custom-ui-tiles/29513/224?u=mariusthvdb please

**Comment by hvbhome** [comment]
![schermafbeelding 2018-03-13 om 21 41 07](https://user-images.githubusercontent.com/33354141/37368729-5931a166-2707-11e8-8bab-01597c3228d7.jpg)


```
    input_text.tiles_lights:
      state_card_custom_ui_secondary: state-card-tiles
      config:
        columns: 3
        row_height: 50px
#        gap: 18 px
        text_size: 1em
        color: '#555B65'
        color_on: '#F0C209'
        color_off: '#555B65'
        entities:
          #Lights
          - entity: group.all_lights_only
#            label: All
            style_template: "return 'text-transform: none; min-height: 20px;';"
            icon_template: "if (state === 'on') return 'mdi:power-plug'; else return 'mdi:power-plug-off'"
            color_on: green
            color_off: red
            column: 3
            row: 1
#            row_span: 1
          - entity: group.buffet_lights
            label: Buffet
            style_template: "return 'text-transform: none;';"
            icon: mdi:pine-tree
            column: 1
            row: 2
#            row_span: 1
          - entity: group.dining_table_lights
            label: Dining
            style_template: "return 'text-transform: none;';"
            icon: mdi:silverware
            column: 2
            row: 2
#            row_span: 1
          - entity: group.terrace_lights
            label: Terrace
            style_template: "return 'text-transform: none;';"
            icon: mdi:nature
            column: 3
            row: 2
#            row_span: 1
          - entity: group.auditorium_lights
            label: Auditorium
            style_template: "return 'text-transform: none;';"
            icon: mdi:theater
            column: 1
            column_span: 2
            row: 3
#            row_span: 1
          - entity: group.living_lights
            label: Living
            style_template: "return 'text-transform: none;';"
            icon: mdi:seat-recline-extra
            column: 3
            row: 3
#            row_span: 1
          - entity: group.hallway_lights
            label: Hallway
            style_template: "return 'text-transform: none;';"
            icon: mdi:exit-to-app
            column: 1
            row: 4
#            row_span: 1
          - entity: group.library_lights
            label: Library
            style_template: "return 'text-transform: none;';"
            icon: mdi:library
            column: 2
            row: 4
#            row_span: 1
          - entity: group.corridor_lights
            label: Corridor
            style_template: "return 'text-transform: none;';"
            icon: mdi:exit-to-app
            column: 3
            row: 4
#            row_span: 1
          - entity: group.master_bedroom_lights
            label: Bedroom
            style_template: "return 'text-transform: none;';"
            icon: mdi:hotel
            column: 1
            row: 5
#            row_span: 1
          - entity: group.mobile_lights
            label: Mobile
            style_template: "return 'text-transform: none;';"
            icon: mdi:transfer
            column: 3
            row: 5
#            row_span: 1
          - entity: light.inside
            label: Inside
            style_template: "return 'text-transform: none;';"
            icon: mdi:ceiling-light
            column: 1
            row: 6
#            row_span: 1
          - entity: light.bureau
            label: Bureau
            style_template: "return 'text-transform: none;';"
            icon: mdi:lamp
            column: 2
            row: 6
#            row_span: 1
          - entity: light.outside
            label: Outside
            style_template: "return 'text-transform: none;';"
            icon: mdi:ceiling-light
            column: 3
            row: 6
#            row_span: 1
```
