### ISSUE TITLE
icon align left, not center

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#26]
## Incomplete issues will be ignored
- [ x] I have read README.md
- [x ] I have deleted my browser cache after updating tiles
- [ ] I run Home Assistant 0.66 or later
- [ ] I don't use dirty hacks like modifying the minimum tile size

**Description of problem:**
```
Icon on tiles are left aligned, no option available to align icons?
```

**Expected:**
```
Icon in the center of the tile
```

**Tiles version shown in HA:**
```
20180314
```

**Affected browser:**
```
Safari Desktop, Safari Ios 11.3
```

**Home Assistant version:**
```
0.65.4
```

**Home Assistant `frontend:` config:**
```yaml
   javascript_version: auto

extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html

    - /local/custom_ui/state-card-value_only.html
    - /local/custom_ui/state-card-tiles.html
    - /local/custom_ui/state-card-table.html
    - /local/custom_ui/state-card-custom_scene.html
    - /local/custom_ui/state-card-text.html

extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
    - /local/custom_ui/state-card-tiles_es5.html
    - /local/custom_ui/state-card-value_only.html
    - /local/custom_ui/state-card-text.html

themes: !include_dir_merge_named frontend_themes
```

**Home Assistant `customize:` config:**
```yaml
 input_text.tiles_switches:
      state_card_custom_ui_secondary: state-card-tiles
      config:
        columns: 4
        column_width: 75px
        row_height: 75px
        gap: 4px
        color: '#555B65' #lightgrey
        color_on: green
        color_off: red
        text_color: "#FFF"
        text_color_on: "#FFF"
        text_color_off: "#FFF"
        text_size: 1em
        text_sec_color: "#FFF"
        text_sec_size: 1em
        text_align: center | left | right
        icon_size: 24px
        entities:
          - entity: switch.sw_audio_auditorium_template
            label: Auditorium
            style_template: "return 'text-transform: none;';"
            icon: mdi:theater
            more_info: switch.sw_audio_auditorium_template
          - entity: switch.sw_tv_auditorium_template
            label: Auditorium
            style_template: "return 'text-transform: none;';"
            icon: mdi:television
          - entity: switch.sw_espresso_keuken_template
            label: Espresso
            style_template: "return 'text-transform: none;';"
            icon: mdi:coffee
          - entity: switch.sw_tv_library_template
            label: Library
            style_template: "return 'text-transform: none;';"
            icon: mdi:library
          - entity: switch.sw_kantoor_template
            label: Kantoor
            style_template: "return 'text-transform: none;';"
            icon: mdi:desktop-mac
          - entity: switch.sw_audio_gym_template
            label_sec: Gym
            style_template: "return 'text-transform: none;';"
            icon: mdi:speaker
          - entity: switch.sw_tester_template
            label: Tester
            style_template: "return 'text-transform: none;';"
            icon: mdi:test-tube
          - entity: switch.sw_dorm_template
            label_sec: Dorm
            style_template: "return 'text-transform: none;';"
            icon: mdi:human-child

```

**Error log from browser dev console - NOT from HA:**
```
NO errors

```

**Screenshot:**
<<here>>
![schermafbeelding 2018-03-14 om 07 57 45](https://user-images.githubusercontent.com/33354141/37387804-35285fce-275e-11e8-96ac-69cb66cde6cf.jpg)

**Comment by c727** [comment]
Check the readme and fix your config, also remove all options that you don't need

**Comment by hvbhome** [comment]
tbh, i wouldn't know what to 'fix', there's no documentation on the icon positioning/alignment. I hazarded a guess and set text_alignement to center only, and that seems to work.

![schermafbeelding 2018-03-14 om 13 34 33](https://user-images.githubusercontent.com/33354141/37402584-772f18e4-278c-11e8-9405-d716f5f20d18.jpg)

not wanting to pullute this topic, still, related to the text and icon in the same setting: when using the `label_sec` option as you can see i do in my fixed setup, the text_color_on is not valid. Can we use the `text_sec_color` for that? should we use `text_sec_color_on` and `text_sec_color_off`?

**Comment by c727** [comment]
Hmz I think I will remove text_sec_color...

Also replace `style_template: "return 'text-transform: none;';"` with `text_uppercase: false` in the grid config part

**Comment by hvbhome** [comment]
text_transform: check, thanks
text_sec_color: wild be nice to be able to specify on and off colors though, maybe even independently from the main text.

related:

when no label is specified and only an icon, this icon is colored through the text_color_on and _off... is that as intended? was a bit of a puzzle ;-)
![schermafbeelding 2018-03-14 om 13 58 08](https://user-images.githubusercontent.com/33354141/37403642-d1b2e57c-278f-11e8-870f-c839b2268cc6.jpg)
![schermafbeelding 2018-03-14 om 13 58 16](https://user-images.githubusercontent.com/33354141/37403643-d1cf9c94-278f-11e8-8915-22f446d97e85.jpg)

code:

```
    input_text.tiles_lights:
      state_card_custom_ui_secondary: state-card-tiles
      config:
        columns: 3
        row_height: 25px
        text_size: 1em
        text_color_on: '#555B65'
        color_on: '#F0C209'
        color_off: '#555B65'
        entities:
          #Lights
          - entity: group.all_lights_only
#            label: All
            style_template: "return 'text_uppercase: false; min-height: 25px;';"
            icon_template: "if (state === 'on') return 'mdi:power-plug'; else return 'mdi:power-plug-off'"
            color_on: green
            color_off: red
            text_color_on: red
            text_color_off: green
```

**Comment by c727** [comment]
```yaml
config:
        columns: 3
        row_height: 25px
        text_uppercase: false # here you should add it
        text_color_on: '#555B65'
        color_on: '#F0C209'
        color_off: '#555B65'
        entities:
```

Yes text color and align is also for the icon
