### ISSUE TITLE
side panel doesn't scroll

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#27]
## Incomplete issues will be ignored
- [x] I have read README.md
- [x] I have deleted my browser cache after updating tiles
- [ ] I run Home Assistant 0.66 or later
- [ ] I don't use dirty hacks like modifying the minimum tile size

**Description of problem:**
```
side panel_custom doesnt scroll all 
```

**Expected:**
```
scrolling side panel to reveal all rows
```

**Tiles version shown in HA:**
```
20180314
```

**Affected browser:**
```
Safari desktop, iOS , Chrome (showing differently though)
```

**Home Assistant version:**
```
0.65.4
```

**Home Assistant `frontend:` config:**
```yaml
<<here>>
```

**Home Assistant `customize:` config:**
```yaml
##########################################################################################
# Tiles: side panel 
# Tiles custom state card for Home Assistant
# source: https://github.com/c727/home-assistant-tiles
# author: https://github.com/c727
#
# in config you define the main grid in the dashboard (was 2x2), 
# in multi you define the position/size for the specific sub-tiles
#
#  Download /www/custom_ui/state-card-tiles.html and 
#   /www/custom_ui/state-card-tiles_es5.html to <config-dir>/www/custom_ui/
# Add it to your configuration.yaml:
# frontend:
#   extra_html_url:
#     - /local/custom_ui/state-card-tiles.html
#   extra_html_url_es5:
#     - /local/custom_ui/state-card-tiles_es5.html
# Run as panel
#
# Also download /panels/tiles.html to <config-dir>/panels/tiles.html
# Add it to your configuration.yaml:
# panel_custom:
#   - name: tiles
#     sidebar_title: Tiles
#     sidebar_icon: mdi:view-dashboard
#     url_path: tiles
#     config:
#       entities:
#         - entity: input_boolean.switch1
#           label: Switch 1
##########################################################################################
name: tiles
sidebar_title: Tiles
sidebar_icon: mdi:view-dashboard
url_path: tiles
config:
  columns: 2
  rows: 4
#  gap: 5 px
  multi:
    - #header: Activities
      row: 1
#      row_span: 1
      #column: 1
#      column_span: 1
      tiles:
        columns: 4
#        rows: 2
        column_width: 75px
        row_height: 75px
#        gap: 4px
        icon_size: 75px
        color: '#555B65' #grey
        color_on: '#F0C209' #green
        color_off: '#555B65' #red
        entities:
          - entity: script.opstaan
            # label: Opstaan
            image: /local/activities/opstaan75.png
          - entity: script.aan_de_slag
            # label: Aan de slag!
            image: /local/activities/aandeslag75.png
          - entity: script.uit_huis
            # label: Uit huis
            image: /local/activities/uithuis75.png
          - entity: script.gym
           # label: Gym
            image: /local/activities/gym75.png
          - entity: script.selamat_makan
           # label: Selamat makan
            image: /local/activities/selamatmakan75.png
          - entity: script.home_theater
           # label: Home theater
            image: /local/activities/hometheater75.png
          - entity: script.naar_bed
          #  label: Naar bed
            image: /local/activities/naarbed75.png

    - #header: Switches
      row: 2
#      row_span: 1
      #column: 1
#      column_span: 1
      tiles:
        columns: 4
        column_width: 75px
        row_height: 75px
#        rows: 2
#        gap: 4px
#        color: lightgrey
        color_on: '#F0C209' #green
        color_off: '#555B65' #red
        entities:
          - entity: switch.sw_audio_auditorium_template
#            label: Auditorium
            icon: mdi:theater
          - entity: switch.sw_tv_auditorium_template
#            label: Auditorium
            icon: mdi:television
          - entity: switch.sw_espresso_keuken_template
#            label: Espresso
            icon: mdi:coffee
          - entity: switch.sw_tv_library_template
#            label: Library
            icon: mdi:library
          - entity: switch.sw_kantoor_template
#            label: Kantoor
            icon: mdi:desktop-mac
          - entity: switch.sw_audio_gym_template
#            label: Gym
            icon: mdi:speaker
          - entity: switch.sw_tester_template
#            label: Tester
            icon: mdi:test-tube
          - entity: switch.sw_dorm_template
#            label: Dorm
            icon: mdi:human-child

    - #header Mode
      row: 3
#      row_span: 1
#      column: 1
#      column_span: 1
      tiles:
        columns: 4
#        rows: 1
        column_width: 75px
        row_height: 75px
#        gap: 4px
        color: '#555B65' #lightgrey
        color_on: '#F0C209'
        color_off: '#555B65'
        text_color: "#FFF"
        text_color_on: "#FFF"
        text_color_off: "#FFF"
        text_size: 1em
        text_sec_color: "#FFF"
        text_sec_size: 1em
        text_align: center | left | right
        icon_size: 75px
        entities:
          - entity: script.mode_normal
           # label: Normal
            image: /local/modes/normal75.png
          - entity: script.mode_developer
           # label: Developer
            image: /local/modes/developer75.png
          - entity: script.mode_kiosk
            # label: Kiosk
            image: /local/modes/kiosk75.png
          - entity: script.mode_full_house
           # label: Full House
            image: /local/modes/fullhouse75.png

    - #header: Lights
      row: 4
#      row_span: 1
      #column: 1
#      column_span: 1
      tiles:
        columns: 4
        column_width: 75px
        row_height: 75px
#        gap: 4 px
        text_size: 1em
        color: '#555B65'
        color_on: '#F0C209'
        color_off: '#555B65'
        entities:
          #Lights
          - entity: group.all_lights_only
#            label: All
            style_template: "return 'text-transform: none;';"
            icon_template: "if (state === 'on') return 'mdi:power-plug'; else return 'mdi:power-plug-off'"
            color_on: green
            color_off: red
            column: 4
            row: 1
#            row_span: 1
          - entity: group.buffet_lights
            label: Buffet
            style_template: "return 'text-transform: none;';"
            icon: mdi:pine-tree
            column: 1
            row: 2
#            row_span: 1
          - entity: group.dining_table_lights
            label: Dining table
            style_template: "return 'text-transform: none;';"
            icon: mdi:silverware
            column: 2
            column_span: 2
            row: 2
#            row_span: 1
          - entity: group.terrace_lights
            label: Terrace
            style_template: "return 'text-transform: none;';"
            icon: mdi:nature
            column: 4
            row: 2
#            row_span: 1
          - entity: group.auditorium_lights
            label: Auditorium
            style_template: "return 'text-transform: none;';"
            icon: mdi:theater
            column: 1
            column_span: 3
            row: 3
#            row_span: 1
          - entity: group.living_lights
            label: Living
            style_template: "return 'text-transform: none;';"
            icon: mdi:seat-recline-extra
            column: 4
            row: 3
#            row_span: 1
          - entity: group.hallway_lights
            label: Hallway
            style_template: "return 'text-transform: none;';"
            icon: mdi:exit-to-app
            column: 1
            row: 4
#            row_span: 1
          - entity: group.library_lights
            label: Library
            style_template: "return 'text-transform: none;';"
            icon: mdi:library
            column: 2
            column_span: 2
            row: 4
#            row_span: 1
          - entity: group.corridor_lights
            label: Corridor
            style_template: "return 'text-transform: none;';"
            icon: mdi:exit-to-app
            column: 4
            row: 4
#            row_span: 1
          - entity: group.master_bedroom_lights
            label: Master Bedroom
            style_template: "return 'text-transform: none;';"
            icon: mdi:hotel
            column: 1
            column_span: 3
            row: 5
#            row_span: 1
          - entity: group.mobile_lights
            label: Mobile
            style_template: "return 'text-transform: none;';"
            icon: mdi:hotel
            column: 4
            row: 5
#            row_span: 1
          - entity: light.inside
            label: Inside
            style_template: "return 'text-transform: none;';"
            icon: mdi:ceiling-light
            column: 1
            row: 6
#            row_span: 1
          - entity: light.bureau
            label: Bureau
            style_template: "return 'text-transform: none;';"
            icon: mdi:lamp
            column: 2
            column_span: 2
            row: 6
#            row_span: 1
          - entity: light.outside
            label: Outside
            style_template: "return 'text-transform: none;';"
            icon: mdi:ceiling-light
            column: 4
            row: 6
#            row_span: 1



```

**Error log from browser dev console - NOT from HA:**
```
No errors
```

**Screenshot:**
safari (wont scroll beyond screen estate):
![schermafbeelding 2018-03-14 om 08 51 59](https://user-images.githubusercontent.com/33354141/37389545-0e44a226-2765-11e8-91b8-54f404813dd3.jpg)

Chrome (shows more but background section beyond screen is awkward)

![schermafbeelding 2018-03-14 om 08 50 11](https://user-images.githubusercontent.com/33354141/37389580-29fc47c6-2765-11e8-96ae-714f0f04aab7.jpg)
