### ISSUE TITLE
dismissing persistent not. messes up Tiles..

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#28]
## Incomplete issues will be ignored
- [ ] I have read README.md
- [ ] I have deleted my browser cache after updating tiles
- [ ] I run Home Assistant 0.66 or later
- [ ] I don't use dirty hacks like modifying the minimum tile size

**Description of problem:**
```
repeatble: whenever a persistent notification appears all seems well. However upon dismissing the notification one of the Tiles cards is completely messed up. Happens with the latest versions of Hassio and Tiles, as well as before.
```

**Expected:**
```
not to happen obviously;-)
```

**Tiles version shown in HA:**
```
20180314
```

**Affected browser:**
```
Safari Mac desktop
```

**Home Assistant version:**
```
various versions before, currently 0.65.4
```

**Home Assistant `frontend:` config:**
```yaml
<<here>>
```

**Home Assistant `customize:` config:**
```yaml
    input_text.tiles_switches:
      state_card_custom_ui_secondary: state-card-tiles
      config:
        columns: 4
        row_height: 50px
        color: '#555B65'
        color_on: '#F0C209'
        color_off: '#555B65'
        text_uppercase: false
        text_color_on: '#555B65'
        text_color_off: "#FFF"
        text_size: 1em
        text_sec_color: "#FFF"
        text_sec_size: 1em
        text_align: center
        icon_size: 24px
        entities:
          - entity: switch.sw_audio_auditorium_template
            label_sec: Auditorium
            icon: mdi:theater
            more_info: switch.sw_audio_auditorium_template
          - entity: switch.sw_tv_auditorium_template
            label_sec: Auditorium
            icon: mdi:television
          - entity: switch.sw_espresso_keuken_template
            label_sec: Espresso
            icon: mdi:coffee
          - entity: switch.sw_tv_library_template
            label_sec: Library
            icon: mdi:library
          - entity: switch.sw_kantoor_template
            label_sec: Kantoor
            icon: mdi:desktop-mac
          - entity: switch.sw_audio_gym_template
            label_sec: Gym
            icon: mdi:speaker
          - entity: switch.sw_tester_template
            label_sec: Tester
            icon: mdi:test-tube
          - entity: switch.sw_dorm_template
            label_sec: Dorm
            icon: mdi:human-child

```

**Error log from browser dev console - NOT from HA:**
```
<<here>>
```

**Screenshot:**
before:
![schermafbeelding 2018-03-14 om 14 42 45](https://user-images.githubusercontent.com/33354141/37406047-8768c00c-2796-11e8-88d8-6fe2ac7ce6a4.jpg)

after:

![schermafbeelding 2018-03-14 om 14 42 57](https://user-images.githubusercontent.com/33354141/37406076-967a2392-2796-11e8-9b52-5862f1adda70.jpg)
