### ISSUE TITLE
Grid Column Auto?

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#31]
question:

Can we set the main grid to Auto also? 
I ask because the default now is 3 (so stating no column number creates a grid of 3 always, no matter of button size), and stating a number always uses that, no matter of resizing windows etc.

If we could use column: Auto, the Card could take care f the positioning of the buttons itself dynamically, based on size of button and Card.
Thus preventing this:

![schermafbeelding 2018-03-16 om 08 25 24](https://user-images.githubusercontent.com/33354141/37508510-a7f73fe8-28f3-11e8-957b-211dd5484abf.jpg)

plenty of space below, too little space in the upper row, which is fixed to 5.

It would be of special interest when viewing the same setup on mobile and desktop, which obviously differ in screen estate. An Auto setting would take care of that. 

this is not what i was hoping for ;-))
![schermafbeelding 2018-03-16 om 08 59 07](https://user-images.githubusercontent.com/33354141/37509630-65261c20-28f8-11e8-9994-7b3920b321b3.jpg)

```
homeassistant:
  customize:
    input_text.tiles_activity:
      custom_ui_state_card: state-card-tiles
      config:
        columns: auto
        column_width: 75px
        row_height: 75px
        color: "var(--paper-card-background-color)"
        background-color: 'green'
        text_align: center
        icon_size: 75px
```

for now I've changed it into:
```
    input_text.tiles_mode:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 4
#        column_width: 75px
#        row_height: 75px
        color: "var(--paper-card-background-color)"
        text_align: center
        icon_size: 75px
```
which takes care of speeding the 4 columns more evenly. Next best thing i guess.
