### ISSUE TITLE
Side panel adjust to full width?

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#32]
Hi

How can we adjust the Tiles side panel automatically to full screen width on mobile device ?

Sure we can trial and error the button widths, but is there a column code or something like that to use?

![mobile](https://user-images.githubusercontent.com/33354141/37553153-6fff4dd6-29c2-11e8-81fc-d62bc3c2a1a1.png)

**Comment by c727** [comment]
column_width: 1f, which is also default

**Comment by hvbhome** [comment]
i have this:

```
name: tiles
sidebar_title: Tiles
sidebar_icon: mdi:view-dashboard
url_path: tiles
config:
  bg_color: "var(--secondary-background-color)"
  title: Tiles sidebar
  header_color: '#F0C209'
  columns: 2
  rows: 4
```

so using default? Still no full screen width is used. Should i state it to be sure?
