### ISSUE TITLE
Tiles not showing up anymore

### ISSUE THREAD

**Issue by PostSven** [c727/home-assistant-tiles#33]
## Incomplete issues will be ignored
- [x] I have read README.md
- [x] I have deleted my browser cache after updating tiles
- [x] I run Home Assistant 0.66 or later
- [x] I don't use dirty hacks like modifying the minimum tile size

**Description of problem:**
```
Tiles are not working anymore
```

**Expected:**
```
Working tiles
```

**Tiles version shown in HA:**
```
20180319
```

**Affected browser:**
```
Firefox, Chrome, IOS App + Safari
```

**Home Assistant version:**
```
HA Docker 0.65.5
```

**Home Assistant `frontend:` config:**
```yaml
frontend:
  javascript_version: es5
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
    - /local/custom_ui/state-card-tiles_es5.html
  themes:
    dark:
      primary-color: '#36454f'
```

**Home Assistant `customize:` config:**
```yaml
homeassistant:
  customize:
    input_text.remote_control:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 2
        row_height: 50px
        column_width: 62px
        gap: 15px
        color: '#555B65'
        color_on: '#D5D619'
        color_off: '#BBBEC2'
        entities:
          - entity: script.scene_allelampenuit
            icon: mdi:hotel
            column: 1
            row: 1
          - entity: script.scene_allelampenaan
            icon: mdi:lightbulb
            column: 2
            row: 1
            
input_text:
  remote_control:
    name: remote_control

script:
  scene_allelampenaan:
    sequence:
      - service: homeassistant.turn_on
        entity_id: scene.allelampenaan
  scene_allelampenuit:
    sequence:
      - service: homeassistant.turn_on
        entity_id: scene.allelampenuit
```

**Error log from browser dev console - NOT from HA:**
```
Firefox/Chrome 2018-03-19 10:39:24 ERROR (MainThread) [frontend.js.es5.201803100] https://assets-cdn.github.com/assets/frameworks-4a1b6c3d0f262c2060b73023efedb0d2.js:1:227877 Uncaught TypeError: Illegal invocation

IOS
2018-03-19 10:40:26 ERROR (MainThread) [frontend.js.es5.201803100] :0:0 Script error.

```

**Screenshot:**
<<here>>
