### ISSUE TITLE
Card shuffling to save vertical height isn't working

### ISSUE THREAD

**Issue by mynameisdaniel32** [c727/home-assistant-tiles#34]
## Incomplete issues will be ignored
- [Y ] I have read README.md
- [ Y] I have deleted my browser cache after updating tiles
- [ Y] I run Home Assistant 0.66 or later
- [ Y] I don't use dirty hacks like modifying the minimum tile size

**Description of problem:**
```
Home Assistant card heights not auto-rearranging when using tiles. I remember seeing something about a setting somewhere to force it to respect group ordering, I'm not using this and had cards auto shuffle before moving to use tiles for most things```
```
**Expected:**
```
Cards to shuffle around between columns to minimise page height. I'm not sure if this is something that can be fixed as part of this or needs to be addressed within Home Assistant / Polymer?
```

**Tiles version shown in HA:**
```
20180320
```

**Affected browser:**
```
All
```

**Home Assistant version:**
```
0.66-dev (2-3 days old)
```

**Home Assistant `frontend:` config:**
```yaml
frontend:
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html
```

**Home Assistant `customize:` config:**
```yaml
Can share relevant sections if required, my customize file is almost 500 lines long.
```

**Error log from browser dev console - NOT from HA:**
```
Nothing relevant.
```

**Screenshot:**
Shows the page on a full size Chrome window (Full HD screen). The lights card that is cut off is actually the longest card on the page.
![image](https://user-images.githubusercontent.com/24840952/37643253-cecebdce-2c6f-11e8-849f-41ba07c2ce49.png)
