### ISSUE TITLE
option for autofill/fontsize shrink?

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#37]
Hi,

Playing with the many tempting options you provide, I ran into this:  
![schermafbeelding 2018-03-28 om 18 10 53](https://user-images.githubusercontent.com/33354141/38042058-98a196dc-32b3-11e8-9519-cd6a9198c09a.jpg)
![schermafbeelding 2018-03-28 om 18 11 02](https://user-images.githubusercontent.com/33354141/38042059-98c47774-32b3-11e8-8ff4-6a744096e14c.jpg)

Is there an 'autofill' option for this, or do I simply have to change the template because I show too much:

relevant bit:

```
    input_text.tiles_switches:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 4
        row_height: 50px
        color_on: '#F0C209'
        color_off: '#555B65'
        text_uppercase: false
        text_color_on: '#555B65'
        text_color_off: '#F0C209'
        text_size: 1em
        text_sec_size: 1em
        text_align: center
        icon_size: 24px
        entities:
          - entity: switch.sw_audio_auditorium_template
            label_sec: Auditorium
            icon: mdi:theater
            more_info: switch.sw_audio_auditorium_template
          - entity: switch.sw_tv_auditorium_template
            label_sec: Auditorium
            icon_template: "if (state === 'on') return 'mdi:television';
                            else return 'mdi:television-off'"
#            icon: mdi:television
          - entity: switch.sw_espresso_keuken_template
#            label_sec: Espresso
#            label_sec_state: sensor.espresso_keuken_actueel
            label_sec_template: "if (state === 'on') return 'Espresso ' + 
                                     entities['sensor.espresso_keuken_actueel'].state;
                                 else return 'Espresso' "
            icon: mdi:coffee

```
