### ISSUE TITLE
Python script support

### ISSUE THREAD

**Issue by pacobyte** [c727/home-assistant-tiles#4]
I have made a control panel using these tiles for my Harmony hub, and I've written a Python script to process which remote command to send based on the current Harmony activity. I use the same configuration as with standard HA scripts, like this:
```yaml
- entity: python_script.harmony_buttons
  icon: mdi:play
  column: 2
  row: 6
  data: {button: Play}
```
However, only the tiles that I created by referencing the `python_script` do not display in the browser (Chrome), and this is the error I receive:
```
Uncaught TypeError: Cannot read property 'state' of undefined
  at HTMLElement.computeClass (state-card-tiles.html:93)
```
I'm assuming that this is because tiles do not currently support using python scripts for the entity option. Is that correct? And if so, do you plan on implementing it?
