### ISSUE TITLE
No Tiles in iOS app

### ISSUE THREAD

**Issue by oakbrad** [c727/home-assistant-tiles#40]
**Description of problem:**
```
Starting in one of the 0.65.x updates, Tiles no longer show up on iOS
```

**Expected:**
```
It works on every other device/browser I have except iOS Safari/HA app.

I cleared the Safari cache, uninstalled and reinstalled the HA app, rebooted the phone, updated HA to 0.66.0, re-downloaded tiles, cleared the cache a few more times, etc.. Nothing.
```

**Tiles version shown in Home Assistant developer info:**
```
Tiles custom state card: 20180401
```

**Affected browser:**
```
Home Assistant iOS app & iOS Safari
```

**Home Assistant version:**
```
0.66.0
```

**Home Assistant `frontend:` config:**
```yaml
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
    - /local/custom_ui/state-card-tiles.html
```

**Home Assistant `customize:` config:**
```yaml
    input_text.tiles_scenes:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 3
        cell_height: 100px
        cell_width: 100px
        entities:
          - entity: script.scene_day_dim
            icon: mdi:weather-sunny
          - entity: script.scene_night_bright
            icon: mdi:weather-sunset
          - entity: script.scene_night_dim
            icon: mdi:weather-night
          - entity: script.everything_off
            label: "ALL OFF"
            column_span: 3
          - entity: script.scene_movie_time
            icon: mdi:movie
          - entity: script.goodnight
            icon: mdi:sleep
          - entity: script.everything_off_milight
            icon: mdi:looks
```

**Error log from browser dev console - NOT from HA:**
```
Not sure how to do this in app.
```

**Screenshot:**

![image-1](https://user-images.githubusercontent.com/24882215/38176787-109c39be-35aa-11e8-82a4-0bf74e0324e5.jpg)
