### ISSUE TITLE
style_template: have button change color based on state input_select

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#41]
please guide me here, if tried to color several buttons (which are scripts, so dont have an On or Off state) based on the state of an input_select, as follows:

```
homeassistant:
  customize:
    input_text.tiles_activity:
      custom_ui_state_card: state-card-tiles
      config:
        columns: auto-fit
        column_width: minmax(75px, 75px)
        color: "var(--paper-card-background-color)"
#        text_align: center
        text_uppercase: false
        icon_size: 75px
        entities:
          - entity: script.opstart_direct
            image: /local/activities/opstart75.png
            style_template: "if (entities['input_select.activity'].state === 'Opstart') return 'color: #F0C209';"
          - entity: script.opstaan_direct
           # label: Opstaan
            image: /local/activities/opstaan75.png
            style_template: "if (entities['input_select.activity'].state === 'Opstaan') return 'color: #F0C209'; else return null';"
```
thought to have followed your instructions before, unfortunately the buttons dont change color.

What should I change? Thanks for having a look,
Marius
