### ISSUE TITLE
Gap option not working after upgrading to 20180401

### ISSUE THREAD

**Issue by jarrah31** [c727/home-assistant-tiles#42]
**Description of problem:**
It appears that the `gap: 10px` grid option is no longer working after upgrading to the latest version, and it was working ok on 20180320.

I upgraded to benefit from the 'unavailable' fix you recently applied (thank you very much for that!), but I noticed straight away that tile gaps are now all at the default 4px. This was particularly noticeable with my window open/close graphic as gaps now appear as seen in the screenshot below.
I also have a before and after screenshot showing the tile gap difference.

I was however on 65.5 so waited reporting this until I could upgrade to 66.1 to see if that helps, but it unfortunately still persists.

I have removed the page cookie and refreshed the cache, and tried different browsers, all with the same problem.

**Tiles version shown in Home Assistant developer info:**
```
Tiles custom state card: 20180401
```

**Affected browser:**
```
Chrome 64 on MacOS, Safari on MacOS
```

**Home Assistant version:**
```
66.1
```

**Home Assistant `customize:` config:**
```yaml
    input_text.single_window:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 1
        row_height: 50px
        column_width: 75px
        gap: 0px
        entities:


    input_text.lights:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 3
        row_height: 30px
        gap: 10px
        text_size: 1em
        color: '#555B65'
        color_on: '#F0C209'
        color_off: '#555B65'
        text_uppercase: false
        entities:
```

**Screenshot:**
Before (input_text.lights):
<img width="470" alt="screen shot 2018-03-30 at 11 04 18" src="https://user-images.githubusercontent.com/3072303/38581281-5118c79e-3d04-11e8-9322-b669b6bb423c.png">
After:
<img width="466" alt="screen shot 2018-04-10 at 21 16 05" src="https://user-images.githubusercontent.com/3072303/38581316-6c03fba0-3d04-11e8-877f-c6cfd16e7098.png">

 input_text.single_window:
<img width="76" alt="screen shot 2018-04-10 at 21 17 03" src="https://user-images.githubusercontent.com/3072303/38581356-8c8a94c4-3d04-11e8-9fdd-338133d4fbcd.png">
