### ISSUE TITLE
color text below icon based on state of other item 

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#44]
**Description of problem:**
```
Trying to color the text below the icon on a button based on the state of an other entity. Ive tested it (both on Chrome and Safari, with   `label_sec_template` and `label_template` with color: , text_color: and text_sec_color: unfortunately no result yet. Asked the forum : https://community.home-assistant.io/t/custom-ui-tiles/29513/326?u=mariusthvdb 

if this is already possible please instruct how to, if not, please read this as a feature request?
thanks,
Marius
```

**Expected:**
```
Color the secondary text below an icon on a button based on the state of another entity
```

**Tiles version shown in Home Assistant developer info:**
```
20180414
```

**Affected browser:**
```
Chrome, safari on Mac and Ios
```

**Home Assistant version:**
```
0.65.5
```

**Home Assistant `frontend:` config:**
```yaml
<<here>>
```

**Home Assistant `customize:` config:**
```yaml
    input_text.tiles_force_switches:
      state_card_custom_ui_secondary: state-card-tiles
      config:
        columns: 3
        row_height: 50px
        text_uppercase: false
        text_size: 1em
#        text_color_on: '#555B65'
#        text_color_off: '#F0C209'
#        color_on: '#F0C209'
#        color_off: '#555B65'
        entities:
          - entity: script.tester_on
            label_sec: 'Tester on'
            style_template: "if (entities['sensor.tester_state'].state === 'on') return 'background-color: #F0C209; color: #555B65';
                              else return 'background-color: #555B65; color: #F0C209;text-decoration: line-through';"
            label_template: "if (entities['sensor.tester_state'].state === 'on') return 'color: #555B65';
                              else return 'text_color: #F0C209';"
            icon_template: "if (entities['sensor.tester_state'].state === 'on') return 'mdi:test-tube';
                              else return 'mdi:test-tube-off';"
#            icon: mdi:test-tube
          - entity: script.tester_off
            label_sec: 'Tester off'
            style_template: "if (entities['sensor.tester_state'].state === 'on') return 'background-color: #555B65;color: #F0C209';
                              else return 'background-color: #F0C209; color: #555B65;text-decoration: line-through';"
            label_template: "if (entities['sensor.tester_state'].state === 'on') return 'color: #555B65';
                              else return 'label_sec_color: #F0C209;';"
            icon: mdi:test-tube
          - entity: script.tester_state
            label_sec: 'Tester State'
            text_color: '#555B65'
            color: '#E5E5E5'

```

**Error log from browser dev console - NOT from HA:**
```
no errors
```

**Screenshot:**
<<here>>
![schermafbeelding 2018-04-16 om 11 23 47](https://user-images.githubusercontent.com/33354141/38800874-a9f3408e-4168-11e8-8efc-ef2df9d04d01.jpg)
