### ISSUE TITLE
On/Off Status Not Being Detected

### ISSUE THREAD

**Issue by jarrah31** [c727/home-assistant-tiles#47]
**Description of problem:**
I've successfully configured a sensor to turn on or off if any of the multiple defined binary sensors change their on/off status, e.g.
sensors.yaml:
```
  - platform: template
    sensors:
      windows_kitchen_open:
        friendly_name: "Kitchen Windows Open"
        value_template: >-
          {%- set windows = [
          "binary_sensor.door_window_sensor_158d0001ab4089",
          "binary_sensor.door_window_sensor_158d0001ab405e",
          "binary_sensor.door_window_sensor_158d0001ab7292"] -%}
          {%- for window in windows if is_state(window, 'on') -%}
            {% if loop.last -%}on{% endif %}
            {% else %}off
          {%- endfor -%}
```
The entities page shows that this appears to be working ok, and when I display the sensor on HA `- sensor.windows_kitchen_open`, it reports as either on or off:
<img width="868" alt="screen shot 2018-05-04 at 18 41 32" src="https://user-images.githubusercontent.com/3072303/39642882-ed8c5284-4fca-11e8-826c-6fd47cfb048a.png">
<img width="858" alt="screen shot 2018-05-04 at 18 42 11" src="https://user-images.githubusercontent.com/3072303/39642886-f0c50cf2-4fca-11e8-8b4c-bf426116845c.png">

The problem is, using this sensor on a tile the colour doesn't change when going between on/off states (the icon_template does change though). Do I perhaps need to define the sensor on/off state in a way other than plain text? 

This is my tile config:
```
    input_text.windows:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 5
        row_height: 50px
        text_size: 1em
        color: '#555B65'
        color_on: 'hsl(0, 100%, 50%)' #red
        color_off: 'hsl(120, 100%, 40%)' #green
        text_uppercase: false
        entities:
          - entity: sensor.windows_kitchen_open
            label_sec: Kitchen
            icon_template: "if (state === 'on') return 'mdi:window-open'; else return 'mdi:window-closed'"
            column: 3
            row: 1
```
This is what they look like. As you can see the window icon has changed to the open state, but the tile isn't turning red for on, nor do the others stay at green for off.
<img width="388" alt="screen shot 2018-05-04 at 18 48 58" src="https://user-images.githubusercontent.com/3072303/39643213-f5e335d2-4fcb-11e8-8771-ee0b77c26e97.png">

Thanks in advance!

**Tiles version shown in Home Assistant developer info:**
```
Tiles custom state card: 20180414
```

**Affected browser:**
```
Safari on MacOS
```

**Home Assistant version:**
```
0.66.1
```

**Comment by hvbhome** [comment]
take out

color: '#555B65' which is the grey your setting for all tiles.

**Comment by jarrah31** [comment]
Hi hvbhome, thank you for the suggestion. Unfortunately the tiles are now just blue and they still don't change colour. I suspect it's something to do with the way On or Off is defined as a string rather than a defined boolean (or something like that).

**Comment by hvbhome** [comment]
if the other tiles do change their icon correctly, you can at least be certain the state is correct.

if so, you could try and experiment with the color definition being used.

also, just as a precaution, this might be a templating issue, and not a Tiles issue, and you'd best take it to the forum...

for experiment's sake, try these colors, which work fine (provided the state you use is correct)

```
        color_on: '#F0C209'
        color_off: '#555B65'
        text_color_on: '#555B65'
        text_color_off: '#F0C209'
```

![schermafbeelding 2018-05-16 om 23 54 21](https://user-images.githubusercontent.com/33354141/40146070-8216c284-5964-11e8-8363-f4caea857ed3.jpg)

**Comment by jarrah31** [comment]
I've done some more testing to see if it is a templating issue by setting up an automation based on the on/off state of the sensor (see below). Good news is that the on state is detected ok as I receive a notification, so at least the template seems to function ok.
```
  - alias: Test sensor template
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - sensor.windows_kitchen_open
      from: 'off'
      to: 'on'
    action:
      - service: notify.teleme
        data_template:
          message: '{{trigger.to_state.attributes.friendly_name}} has been triggered'
```
I've also tried your suggestion with the text colour, but the text just remains white. The icon continues to change ok too.
