### ISSUE TITLE
feature request: allow attribute.entity_picture

### ISSUE THREAD

**Issue by hvbhome** [c727/home-assistant-tiles#50]
HI

using the 

  ```
          style_template: >
              return 'background-image: url(\"/local/tiles/' + state + '75.png\")';

```

works fine, but is really very specific about case and spaces in the name. Had to create dedicated picture names for these entities:

![schermafbeelding 2018-06-08 om 08 05 10](https://user-images.githubusercontent.com/33354141/41141571-b2b2171e-6af2-11e8-83b4-8a17e606d426.jpg)

frontend names are not always the same as backend filenames.

If you'd allow using the attribute.entity_picture, as all other attributes are allowed we could simply state:

`style_template: return attribute.entity_picture`

much easier, no errors lurking and consistent with the overall logic.

Please consider.
Cheers,
Marius

**Comment by hvbhome** [comment]
not much in the docs, other than the example.. i've read them all, and got it working alright, albeit with a workaround, but maybe im just missing the exact correct syntax.

btw, talking about the docs:

entity option `image:` isnt there, and very useful in implementation , so maybe add it to the Docs?

```
        entities:
          - entity: script.mode_normal_direct
            image: /local/modes/normal75.png
            label: Normal
```

having an image_template lures..
