### ISSUE TITLE
Tiles not displaying on mobile 63.3

### ISSUE THREAD

**Issue by andrewlozoya** [c727/home-assistant-tiles#7]
```
input_text.tiles:
  custom_ui_state_card: state-card-tiles
  config:
    columns: 1
    column_width: 75px
    row_height: 75px
    gap: 15px
    color: '#36454F'
    color_on: '#0F9D58'
    color_off: '#36454F'
    entities:
      - entity: switch.ceiling
        icon: mdi:ceiling-light

```
Log Details (ERROR)

Sat Feb 17 2018 22:38:59 GMT-0600 (Central Standard Time)

undefined:1:11 TypeError: Cannot call a class constructor without |new|

Hassbain 63.3

IOS Native Browser and Hybrid Home Assistant App

**Comment by c727** [comment]
https://github.com/c727/home-assistant-tiles/issues/new

**Comment by andrewlozoya** [comment]
It is working now please double check your configuration file I believe you have the wrong es5 HTML file listed 

```
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
- /local/custom_ui/state-card-tiles.html
```

it should be 

```
  extra_html_url_es5:
- /local/custom_ui/state-card-tiles_es5.html
```
